### ISSUE TITLE
type generator: Support debugger-specific arguments in LaunchRequestArguments

### ISSUE THREAD

**Issue by polinasok** [google/go-dap#20]
For example, LaunchRequestArguments in vscode-go calling delve might contain the following implementation specific attributes:
"name":"Launch",
"type":"go",
"request":"launch",
"mode":"debug",
"program":"/Users/foo/go/src/helloworld",
"env": {...} ,
"args:[],
"showLog":true,
"trace":"log",
"logOutput":"rpc",
"stopOnEntry":true,
... etc...
See the following for more information:
https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-launchjson
https://github.com/microsoft/vscode-go/blob/be0cc9ed9cd9a7eb5e8501197c8551458fbc2aaf/package.json#L409

**Comment by polinasok** [comment]
The easiest thing is to just replace LaunchRequestArguments with map[string]inteface{}. json.Unmarshall will unpack that part of the request into the map instead of a struct - see https://play.golang.org/p/WuvLtmMjULV for example.

**Comment by eliben** [comment]
Thanks for checking. I'll work on it
