### ISSUE TITLE
question: is there anyway to test this ?

### ISSUE THREAD

**Issue by apmattil** [google/go-dap#33]
I'm now using emacs with dap-mode.

is the idea integrate this with dlv ? 
or is there way to test this as stand alone ? replace nodejs + vscode extension at dap-mode.

**Comment by eliben** [comment]
The idea is to integrate this in delve; this is tracked in https://github.com/go-delve/delve/issues/1515 

Once it's integrated in delve, emacs may be able to significantly simplify its dap-mode.

**Comment by apmattil** [comment]
ok, thank you.
