### ISSUE TITLE
Type Breakpoint contains empty `source`

### ISSUE THREAD

**Issue by corneliusweig** [google/go-dap#66]
The Breakpoint is defined as 

```go
type Breakpoint struct {
	Id                   int    `json:"id,omitempty"`
	Verified             bool   `json:"verified"`
	Message              string `json:"message,omitempty"`
	Source               Source `json:"source,omitempty"`
	Line                 int    `json:"line,omitempty"`
	Column               int    `json:"column,omitempty"`
	EndLine              int    `json:"endLine,omitempty"`
	EndColumn            int    `json:"endColumn,omitempty"`
	InstructionReference string `json:"instructionReference,omitempty"`
	Offset               int    `json:"offset,omitempty"`
}
```

It says `"source,omitempty"`, but an empty object is serialised as:

```go
data, _ := json.Marshal(dap.Breakpoint{})
fmt.Println(string(data))

// {"verified":false,"source":{}}
//                     ^^^^^^^^
```

This means that `BreakpointEvent` types with _missing_ source are serialised with an _empty_ source object, which clears the breakpoint location in the UI.

**Can the `Source` field be changed to a pointer field instead?**

**Comment by hyangah** [comment]
Thanks for the bug report.
Can you help us find the part in the spec that explains the editor's behavior you were observing? More specifically, I want to understand why the editor is clearing the breakpoint location when seeing completely empty `Source` object.

**Comment by corneliusweig** [comment]
The spec is a bit vague, but I think it's there:

1. The documentation for `BreakpointEvent` (https://microsoft.github.io/debug-adapter-protocol/specification#Events_Breakpoint) says:

    ```ts
        /**
         * The `id` attribute is used to find the target breakpoint, the other
         * attributes are used as the new values.
         */
        breakpoint: Breakpoint;
    ```
    
    I think the phrase *the other attributes are used as the new values* means that whatever is specified in the breakpoint updates existing values.

1. The Breakpoint type has an optional source field (https://microsoft.github.io/debug-adapter-protocol/specification#Types_Breakpoint):

    ```ts
      /**
       * The source where the breakpoint is located.
       */
      source?: Source;
    ```

Taken together, I think it makes sense to read it as "when present, the source field updates existing values".

**Note:** All fields in the `Source` type are optional. However, if they would always be merged into the existing values, it would be impossible to clear fields. Therefore, I think it does not make sense to assume that an empty `Source` gets merged into an existing one.

**Comment by suzmue** [comment]
I agree that fixing this bug makes sense.

Some initial investigation in the vscode source VS Code seems that it handles undefined differently than zero (https://github.com/microsoft/vscode/blob/9dba5385c7aefebe3756ed413da7fedf1868a71c/src/vs/workbench/contrib/debug/common/debugModel.ts#L966).

Delve does not yet use BreakpointEvents to update breakpoints. Delve sends all information about breakpoints through the response to the setBreakpoints requests.

**Comment by corneliusweig** [comment]
Thank you! I tentatively created a PR for this trivial change.

If this is fixed for `Breakpoint.Source`, there are a few other places that should possibly be updated too. I found a few fields that are marked as `omitempty`, but are struct types, so they would be serialised as empty objects as described above. Additional fields I could imagine are problematic are:

- `DisassembledInstruction.Location`
- `Scope.Source`
- `SetExpressionResponseBody.PresentationHint`
- `EvaluateResponseBody.PresentationHint`
